#include "SumProductBP.h"
#include "BetaStepBP.h"
#include "ProjectionBP.h"
#include "AProjectionBP.h"
#include "ZoomBP.h"
#include "FastZoomBP.h"
// #include "NewZoomBP.h"
#include "KProjectionBP.h"
#include "StochasticBP.h"
#include "StochasticBP2.h"
